server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5432/concert
spring.datasource.username=postgres
spring.datasource.password=anime021
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=/0Jiuf7OkR++rAitSZ1Jf3qprwv4ZizZC/1ICmg8OOk=
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.info.title=Concert Book API
springdoc.info.version=1.0
springdoc.info.description=API documentation for Concert Booking System